# Generated by Django 5.0.3 on 2024-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='other_attendance_type',
            field=models.CharField(blank=True, help_text="Specify if attendance type is 'Others'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Offsite', 'Offsite'), ('WFH', 'Work from Home'), ('Leave', 'Leave'), ('Travel', 'Travel'), ('Others', 'Others')], default='Onsite', max_length=20),
        ),
    ]
