# Generated by Django 5.0.3 on 2024-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_attendance_other_attendance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
