# Generated by Django 5.0.3 on 2024-11-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_staff_leave_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Offsite', 'Offsite'), ('WFH', 'Work from Home'), ('Leave', 'Leave'), ('Travel', 'Travel'), ('Others', 'Others'), ('Paid_Leave', 'Paid_Leave')], default='Onsite', max_length=20),
        ),
    ]
