# Generated by Django 5.0.3 on 2024-11-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_attendance_attendance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='remaining_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='insurance_policy_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
