# Generated by Django 5.0.3 on 2024-11-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_staff_remaining_leave_alter_staff_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='total_leaves',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='staff',
            name='remaining_leave',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
