# Generated by Django 5.0.3 on 2024-11-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_staff_total_leaves_alter_staff_remaining_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='remaining_leave',
        ),
        migrations.AddField(
            model_name='staff',
            name='remaining_leaves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='total_leaves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
