# Generated by Django 5.0.3 on 2024-11-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_staff_remaining_leave_staff_remaining_leaves_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='remaining_leaves',
            new_name='remaining_leave',
        ),
    ]
