# Generated by Django 5.0.3 on 2024-11-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_rename_remaining_leaves_staff_remaining_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
