# Generated by Django 5.0.3 on 2024-11-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_staff_remaining_leaves_staff_total_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='remaining_leaves',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='total_leaves',
        ),
    ]
