# Generated by Django 5.0.3 on 2024-11-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_remove_staff_remaining_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='totalleaves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
