# Generated by Django 5.1.2 on 2024-12-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_attendance_location_alter_attendance_attendance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='location',
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_type',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Ahmedabad', 'Ahmedabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow')], default='', max_length=20),
        ),
    ]
