# Generated by Django 5.1.2 on 2024-12-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_remove_attendance_location_attendance_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='location_type',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Offsite', 'Offsite'), ('WFH', 'Work from Home'), ('Leave', 'Leave'), ('Travel', 'Travel'), ('Others', 'Others'), ('Paid_Leave', 'Paid_Leave')], default='Onsite', max_length=20),
        ),
    ]
