# Generated by Django 5.0.3 on 2024-12-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_remove_attendance_location_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the attendance is marked', max_length=100, null=True),
        ),
    ]
